### ISSUE TITLE
Proposal: Move Documentation to Repository Wiki

### ISSUE THREAD

**Issue by l-zeuch** [l-zeuch/yagpdb.vim#15]
### Description

As it stands, we have quite a substantial and rather massive README file, consisting of installation instructions and other irrelevant information to the development of this project.

### Solution

Because the README file is, in my opinion, meant for *contributors* and developers rather than users, I suggest that we move all such irrelevant information to the repository's [wiki](https://github.com/l-zeuch/yagpdb.vim/wiki), which is meant for users.

Of course, it might be not that much currently, however in the long run, as this project grows, it is definitely a feasible option to do so.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by LRitzdorf** [comment]
Agreed, that makes sense. We should probably link the wiki in the new README, though, in case normal users do read it.

**Comment by jo3-l** [comment]
> Because the README file is, in my opinion, meant for contributors and developers rather than users, I suggest that we move all such irrelevant information to the repository's wiki, which is meant for users.

While this is certainly a valid standpoint — and I recognize that it's meant as an opinion as opposed to fact — many major projects do include information for end users in READMEs, so it isn't like the current contents are unusual in any way. (Conversely, many projects choose to place information directed toward end users elsewhere, so the choice to move it away is not strictly incorrect.)

---

With that said, there are numerous downsides to using the wiki to store information directed toward end users, including but not limited to the following:

- Edit access to wikis is either "only collaborators are edit" or "everyone can edit"; the first makes outside contributions from non-collaborators unnecessarily difficult, whereas the second is a nightmare to moderate
- Decoupling the wiki from the project makes it easier to forget to update documentation along with code changes; additionally, users that clone the repository will not be able to directly access related information
- Git history is harder to access for wikis, making it harder to view recent changes

As the maintainers of the project, the ultimate decision evidently lies with you. Personally, I don't feel strongly as to whether the end user-facing information should be moved elsewhere, but I do hope that GitHub Wiki's pros and cons are considered in depth before the switch is made if it is to be the location of said information.

**Comment by jo3-l** [comment]
> Thus, I suggest to keep only the most important information in the README, which would be installation instructions, and instead copy it over to the documentation located in /doc at the project's root -- this directory will be populated with yagpdb's custom command templates and I feel like it can be populated with this plugin's documentation, too (see https://github.com/l-zeuch/yagpdb.vim/pull/13).

If the intent is to move information away from the README (which is, again, reasonable) I agree with that a `doc/` subdirectory is a good place to put it. In my opinion, though, the README is far from cluttered currently -- the end-user-facing information is not so extensive that it detracts from the parts meant for contributors, making moving it away a less pressing matter.

In the end, the decision is of course up to you as the maintainer of this repository -- I think all your points are quite valid and it comes down really to preference.

**Comment by l-zeuch** [comment]
> In my opinion, though, the README is far from cluttered currently -- the end-user-facing information is not so extensive that it detracts from the parts meant for contributors, making moving it away a less pressing matter.

I'm thinking about restructuring the README to be more sound and, well, readable. Might be a bit overkill for now, though. However, if there's information with regards to documenting configuration, it should be under one section, a.k.a. in one place.

> In the end, the decision is of course up to you as the maintainer of this repository -- I think all your points are quite valid and it comes down really to preference.

Though true it's still important to hear different opinions :stuck_out_tongue_winking_eye:

**Comment by l-zeuch** [comment]
After thinking about this for a while, I don't see any real benefit of having duplicate work in the README and the wiki, and as such, will close this issue as wontfix. Do let me know if you object to that.
