### ISSUE TITLE
Proposal: Setup Vint (Vim Lint)

### ISSUE THREAD

**Issue by l-zeuch** [l-zeuch/yagpdb.vim#16]
### Description

As the codebase grows and contributions are made, some sort of linting and basic code check for correctness should be made, mainly for consistency reasons.

### Solution

Thus, I propose to setup [vint](https://github.com/Vimjas/vint), a highly extensible linter for the Vim Script language.

It is moreover a rather easy task to set up a workflow launching said software, for which I'd be happy to submit a pull request.

Let me know what you think.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by LRitzdorf** [comment]
Sounds good! More code consistency is always helpful.

**Comment by l-zeuch** [comment]
Great!

I'll set it up then!
