### ISSUE TITLE
[Bug]: `g:yagpdbcc_override_ft` without effect

### ISSUE THREAD

**Issue by l-zeuch** [l-zeuch/yagpdb.vim#33]
### Expected Behaviour

For `*.go.tmpl` and `.gotmpl` files:
```vim
:set verbose ft?
filetype=yagpdbcc
```

### Actual Behaviour

Without another's plugin interference:
For `*.go.tmpl` files:
```vim
:set verbose ft?
filetype=template
```
`*.gotmpl` files are working as expected.

### Steps to Reproduce

In `init.vim`
```vim
let g:yagpdbcc_override_ft = 1
lua << EOF
require('plugins')
EOF
```
in `lua/plugins.lua` with [packer.nvim](https://github.com/wbthomason/packer.nvim):
```lua
return require('packer').startup({function(use)
    use 'l-zeuch/yagpdb.vim'
end
})
```

### Additional Context

I've confirmed that this only happens for files with `*.go.tmpl` extensions, even with fatih/vim-go loaded and active (which was the initial reason for #32 and #14). Overriding associations for `*.gotmpl` works as expected.

<details>
<summary>Nvim version</summary>

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by LRitzdorf** [comment]
Repro'd as well. I can look into this later — an initial guess might be that we're either loading too early (and being overridden by the built-in `template` filetype) or somehow still bailing out instead of overriding the existing filetype.

**Comment by l-zeuch** [comment]
With the latest Neovim version on Arch Linux (Neovim 0.7.0), this issue still occurs, just as a heads-up.

I'm quite baffled why even it occurs -- at this point, I'm willing to close this as wontfix, because it is just such a strange and weird behaviour. However, it *must* have to do something with our filetype detection.

**Comment by LRitzdorf** [comment]
Found the issue! See [ftdetect/yagpdbcc.vim:39](https://github.com/l-zeuch/yagpdb.vim/blob/3a12f5e43750de173ea46f0ecff6ae9a7eb3e40b/ftdetect/yagpdbcc.vim#L39). We use `setfiletype`, which will not override an existing filetype, per `:h setfiletype`.

I'll commit a patch for this in just a moment... Fix is based on https://vi.stackexchange.com/a/28427.

**Comment by l-zeuch** [comment]
Wow! That was some elusive bug... Glad you found it!
