### ISSUE TITLE
Proposal: Makefile: Deal with Windows

### ISSUE THREAD

**Issue by LRitzdorf** [l-zeuch/yagpdb.vim#48]
### Description

It is possible to [install GNU `make` on Windows](https://stackoverflow.com/a/32127632).

Currently, our Makefile is untested on Windows, and is likely to misbehave at best. We can try to detect the current OS, and react as we deem appropriate.

### Solution

Windows OS detection can apparently be accomplished with:

```make
ifeq ($(OS),Windows_NT)
	@echo 'Do stuff here...'
endif
```

If we detect that we are running on Windows, we have two main options:
1) Return an error message and exit
    - Plugin managers are, in my experience, quite usable on Windows, with proper configuration, so we might recommend this in our message
1) Change the appropriate paths and install anyway
    - I believe this also changes depending on whether Vim or Neovim is in use
    - Higher complexity

I personally feel that the first option is perfectly acceptable, since anyone who's running Vim and Make on Windows should be comfortable configuring things themselves.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by l-zeuch** [comment]
+1 on recommending a plugin manager in case of installing on Windows, everything else is rather weird to handle, already took a look into it and (Neo)vim files can be in several locations for one user...
