### ISSUE TITLE
[Feature] Yank to System Clipboard

### ISSUE THREAD

**Issue by LRitzdorf** [l-zeuch/yagpdb.vim#6]
This issue serves as a record of a proposed feature for this extension. I'll be implementing it myself soon (probably tonight, if I have nothing better to do), but having a place for discussion might be helpful.

## Rationale

Since YAGPDB CCs are managed though the online dashboard, they must be copy/pasted when edits are made in another platform. With a standard GUI editor like VSCode, this isn't too painful, especially with the <kbd>Ctrl + A</kbd> shortcut, but when using a terminal editor like Vim, it can be painful (especially if you have line numbers enabled, or another pane on the side). As such, a function (which can be bound to a shortcut by the user) would be quite useful.

## Notes

(N)Vim can access the system clipboard using the `"*` and `"+` registers. `"+` *seems* to be the preferred one, though I'm not certain about that. On Windows, both appear to work equivalently, and do in fact add to the Clipboard History feature.

Syntax here is just like with any other register - yank to it using `"+y{motion}` or `{Visual}"+y`, and paste with `"+p`.

**Comment by LRitzdorf** [comment]
To clarify, creating a command with that mapping was the idea. I might not have been very clear about that before. And yeah, definitely something short and memorable. IIRC, plugin commands usually start with a capital letter, so maybe `Yagcp` or something? (`cp` as in "copy," of course)

Also, yes, a test would be great (although this is a Vim feature that shouldn't ever change)

**Comment by l-zeuch** [comment]
Uppercase letters, I've seen that quite a lot, so that would make sense if that is the convention (probably also to prevent possible conflicts with editor commands).

`:Yagcp` I feel like is -- although shorter -- less idiomatic (cp is also commonly used for "control panel" in YAGPDB context, which might be confusing). `:YagCopy` sounds like a better alternative, though I'm up for discussing that.
