### ISSUE TITLE
Proposal: Deprecate Some File Extensions

### ISSUE THREAD

**Issue by l-zeuch** [l-zeuch/yagpdb.vim#79]
### Description

Currently, we support a plethora of file extensions, namely the
following:

https://github.com/l-zeuch/yagpdb.vim/blob/83f3fae0e463b191571d8d20dbf14500fe1b37a0/ftdetect/yagpdbcc.vim#L31-L38

This is certainly a lot, and potentially way too much. There are also
some potential issues with a hyphenated file extension (just a gut
feeling, I haven't tested it) — moreover, long file extensions are just
*really weird*.

### Solution

I propose we drop support for `yagpdb`, `yagpdbcc`, `yag-cc`, and
`yagpdb-cc` in favour of just `yag` and *maybe* `yagcc`. The option to
override `tmpl` and `go.tmpl` should be kept, though, as
[yagpdb-cc/yagpdb-cc](github.com/yagpdb-cc/yagpdb-cc) uses the latter one (for whatever reason, Joe
doesn't remember why).

Obviously this will be a breaking change, and thus needs proper
announcement, at the very least inside the commit message. Keeping this
issue open for a while will also help with that.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by l-zeuch** [comment]
For the record, I've implemented the proposed changes in #80.

If there are any comments on this proposal, please post them in this thread.

**Comment by LRitzdorf** [comment]
Sounds good to me! I do agree that having so many supported extensions is a bit weird.
