### ISSUE TITLE
Consider Using `yagfuncdata`

### ISSUE THREAD

**Issue by l-zeuch** [l-zeuch/yagpdb.vim#82]
### Discussed in https://github.com/l-zeuch/yagpdb.vim/discussions/64

<div type='discussions-op-text'>

<sup>Originally posted by **jo3-l** August  1, 2022</sup>
https://github.com/jo3-l/yagfuncdata is a little CLI tool I wrote to
automatically fetch names of YAGPDB template functions. From the README:
> yagfuncdata aims to simplify workflows of projects that require a list
> of YAGPDB template functions, such as language support extensions for
> editors. For example, one could imagine setting up a cronjob in CI to
> run yagfuncdata regularly to check for updates and regenerate some
> asset file if anything changed.
>
> Note, however, that it is not recommended to run yagfuncdata directly
> as part of an application as the command is not infallible. Changes to
> the structure of relevant files defining template functions may cause
> the generated list to be incomplete or downright wrong. (We elaborate
> on why this is the case below.) Thus, its output should be manually
> vetted by a human against a reliable baseline.

Perhaps `yagfuncdata` could be of use to this project, which seems to
maintain a similar list as part of the syntax definition that requires
manual updating.</div>

----

I'll be working on this in the coming week. A sample of the output
follows.

```shellsession
$ go install github.com/jo3-l/yagfuncdata/cmd/lytfs@latest
$ lytfs
editMessage
editMessageNoEscape
pinMessage
# [...]
```

I'm fine with us parsing this output line-by-line and then doing the
following to `syntax/yagpdbcc/functions.vim`:
```vim
syn keyword yagFunc editMessage contained
syn keyword yagFunc editMessageNoEscape contained
syn keyword yagFunc pinMessage contained
" [...]
```

Obviously, this will really bloat that file up — however I think this is
the easiest `sh` / `Python` / whatever way achievable without having to
do some funky character counting to adhere to our max line width as
specified in `.editorconfig`.

In case you're opposed to that idea, do let me know — we'll be marking
that file as generated as well via `.gitattributes`, just to be on the
safe(r) side.

As Joe outlined, the possibly simplest way would be to use the `cron`
feature of GitHub's workflows.

Of course this workflow will create an automated PR we still have to
manually review (just in case), but it'll be a lot less work than us
updating the list.
Compatibility to the `make generate` target will be kept as far as I
can tell. (It's been a while since I wrote that script).

Though I still will want to have a script that can be run locally to
generate the list, so that users can easily update it themselves,
should they want to.

Tangentially, I'll also be filing a feature request at `yagfuncdata` for
a flag to pass a custom URL and suchlike, to make the above also
possible for custom forks of YAGPDB.

**Comment by LRitzdorf** [comment]
This sounds great! I'm guessing this is already a feature for GH Actions, but we should obviously avoid generating a PR (or any commit, for that matter) when no changes occur as a result of the cron job running.

Also, I may look into the automated line wrapping thing — it very much feels like that should be doable.

**Comment by l-zeuch** [comment]
> This sounds great! I'm guessing this is already a feature for GH
> Actions, but we should obviously avoid generating a PR (or any commit,
> for that matter) when no changes occur as a result of the cron job
> running.

We'll just check `git status` or other status-checking commands if there
were changes. The only problem with that is if the output of `lytfs`
is non-deterministic and can change between runs.
As far as I was able to see however this is not the case, so we're good
to go on that front.

> Also, I may look into the automated line wrapping thing — it very much
> feels like that should be doable.

Sure, go ahead — I was playing around with trying to do it in just the
`Makefile` we have, but ran into a lot of headache-inducing funkiness
that is GNU Make, so I'll probably stick to just a shell script.

Alternatively we can write (one more) Python script that does the job,
whatever is easier. With your line wrapping thing I'm daring to say we
should _probably_ use Python.

In addition to this, I'm also not super stoked about the idea of writing
a shell script, because that would mean we'd have to add yet another
linter to our test suite and there's basically just `shellcheck`. Which,
as far as I can tell, is really only for Bash.

I'm most likely to just write a crude first implementation in Python,
and then we can add the final touches later.

**Comment by l-zeuch** [comment]
Done with the merge of #83.
